window.CTP_PLACES_DATA = [
  {
    "id": 1,
    "name": "Quinoa",
    "city": "Florence",
    "country": "Italy",
    "category": "Restaurant",
    "badge": "Dedicated GF",
    "badge_class": "green",
    "address": "Vicolo di Santa Maria Maggiore 1, Florence",
    "lat": 43.774,
    "lng": 11.2522,
    "status": "starter_verified",
    "gf_notes": "100% gluten free restaurant.",
    "city_url": "/florence.html"
  },
  {
    "id": 2,
    "name": "Sgrano",
    "city": "Florence",
    "country": "Italy",
    "category": "Bakery",
    "badge": "Dedicated GF",
    "badge_class": "green",
    "address": "Via dei Neri 34R, Florence",
    "lat": 43.7693,
    "lng": 11.2588,
    "status": "starter_verified",
    "gf_notes": "Dedicated gluten free bakery and breakfast stop.",
    "city_url": "/florence.html"
  },
  {
    "id": 3,
    "name": "Osteria dello Sgrano",
    "city": "Florence",
    "country": "Italy",
    "category": "Restaurant",
    "badge": "Dedicated GF",
    "badge_class": "green",
    "address": "Via dei Benci 30, Florence",
    "lat": 43.7684,
    "lng": 11.2629,
    "status": "starter_verified",
    "gf_notes": "Dedicated gluten free restaurant concept.",
    "city_url": "/florence.html"
  },
  {
    "id": 4,
    "name": "Mama Eat Firenze",
    "city": "Florence",
    "country": "Italy",
    "category": "Restaurant",
    "badge": "Verified mixed kitchen",
    "badge_class": "yellow",
    "address": "Via della Madonna della Tosse 12R, Florence",
    "lat": 43.7768,
    "lng": 11.2583,
    "status": "starter_verified",
    "gf_notes": "Structured gluten free menu in a mixed kitchen context.",
    "city_url": "/florence.html"
  },
  {
    "id": 5,
    "name": "New Food Experience",
    "city": "Rome",
    "country": "Italy",
    "category": "Restaurant",
    "badge": "Dedicated GF",
    "badge_class": "green",
    "address": "Via Ostiense 73F, Rome",
    "lat": 41.8697,
    "lng": 12.4802,
    "status": "starter_verified",
    "gf_notes": "Dedicated gluten free option in Rome starter dataset.",
    "city_url": "/rome.html"
  },
  {
    "id": 6,
    "name": "Celiachiamo Lab",
    "city": "Rome",
    "country": "Italy",
    "category": "Bakery",
    "badge": "Dedicated GF",
    "badge_class": "green",
    "address": "Via dei Falegnami 9, Rome",
    "lat": 41.8945,
    "lng": 12.4798,
    "status": "starter_verified",
    "gf_notes": "Dedicated gluten free bakery/lab concept.",
    "city_url": "/rome.html"
  },
  {
    "id": 7,
    "name": "Mama Eat Roma",
    "city": "Rome",
    "country": "Italy",
    "category": "Restaurant",
    "badge": "Verified mixed kitchen",
    "badge_class": "yellow",
    "address": "Via di San Cosimato 7, Rome",
    "lat": 41.888,
    "lng": 12.4711,
    "status": "starter_verified",
    "gf_notes": "Mixed kitchen with structured GF management.",
    "city_url": "/rome.html"
  },
  {
    "id": 8,
    "name": "Officina Zero",
    "city": "Milan",
    "country": "Italy",
    "category": "Bakery",
    "badge": "Dedicated GF",
    "badge_class": "green",
    "address": "Via Thaon di Revel 3, Milan",
    "lat": 45.489,
    "lng": 9.1879,
    "status": "starter_verified",
    "gf_notes": "Dedicated gluten free bakery in Milan.",
    "city_url": "/milan.html"
  },
  {
    "id": 9,
    "name": "Via dalla Spiga",
    "city": "Milan",
    "country": "Italy",
    "category": "Bakery",
    "badge": "Dedicated GF",
    "badge_class": "green",
    "address": "Via della Spiga 52, Milan",
    "lat": 45.4719,
    "lng": 9.1984,
    "status": "starter_verified",
    "gf_notes": "Dedicated pastry and bakery reference.",
    "city_url": "/milan.html"
  },
  {
    "id": 10,
    "name": "Mama Eat Milano",
    "city": "Milan",
    "country": "Italy",
    "category": "Restaurant",
    "badge": "Verified mixed kitchen",
    "badge_class": "yellow",
    "address": "Via Giulio Cesare Procaccini 32, Milan",
    "lat": 45.4861,
    "lng": 9.1697,
    "status": "starter_verified",
    "gf_notes": "Mixed kitchen with structured gluten free menu.",
    "city_url": "/milan.html"
  },
  {
    "id": 11,
    "name": "Zero Zero Grano",
    "city": "Naples",
    "country": "Italy",
    "category": "Restaurant",
    "badge": "Dedicated GF",
    "badge_class": "green",
    "address": "Via San Pasquale 27, Naples",
    "lat": 40.8354,
    "lng": 14.2407,
    "status": "starter_verified",
    "gf_notes": "Dedicated gluten free reference in Naples starter data.",
    "city_url": "/naples.html"
  },
  {
    "id": 12,
    "name": "Leopoldo Gluten Free",
    "city": "Naples",
    "country": "Italy",
    "category": "Bakery",
    "badge": "Verified mixed kitchen",
    "badge_class": "yellow",
    "address": "Via Toledo 214, Naples",
    "lat": 40.8428,
    "lng": 14.2482,
    "status": "starter_verified",
    "gf_notes": "Known GF-oriented bakery stop in Naples.",
    "city_url": "/naples.html"
  },
  {
    "id": 13,
    "name": "Prato GF Sample",
    "city": "Prato",
    "country": "Italy",
    "category": "Restaurant",
    "badge": "Verified mixed kitchen",
    "badge_class": "yellow",
    "address": "Central Prato starter record",
    "lat": 43.8798,
    "lng": 11.0965,
    "status": "starter_expansion",
    "gf_notes": "Starter expansion record for Prato.",
    "city_url": "/prato.html"
  },
  {
    "id": 14,
    "name": "Prato GF Hotel Sample",
    "city": "Prato",
    "country": "Italy",
    "category": "Hotel",
    "badge": "Verified mixed kitchen",
    "badge_class": "yellow",
    "address": "Central Prato hospitality starter record",
    "lat": 43.8784,
    "lng": 11.1024,
    "status": "starter_expansion",
    "gf_notes": "GF hospitality starter for Prato.",
    "city_url": "/prato.html"
  },
  {
    "id": 15,
    "name": "Pistoia GF Sample",
    "city": "Pistoia",
    "country": "Italy",
    "category": "Restaurant",
    "badge": "Verified mixed kitchen",
    "badge_class": "yellow",
    "address": "Central Pistoia starter record",
    "lat": 43.933,
    "lng": 10.9179,
    "status": "starter_expansion",
    "gf_notes": "Starter expansion record for Pistoia.",
    "city_url": "/pistoia.html"
  },
  {
    "id": 16,
    "name": "Pistoia GF Hotel Sample",
    "city": "Pistoia",
    "country": "Italy",
    "category": "Hotel",
    "badge": "Verified mixed kitchen",
    "badge_class": "yellow",
    "address": "Central Pistoia hospitality starter record",
    "lat": 43.9344,
    "lng": 10.9206,
    "status": "starter_expansion",
    "gf_notes": "GF hospitality starter for Pistoia.",
    "city_url": "/pistoia.html"
  },
  {
    "id": 17,
    "name": "Bologna Expansion Guide",
    "city": "Bologna",
    "country": "Italy",
    "category": "City Guide",
    "badge": "Expansion",
    "badge_class": "yellow",
    "address": "Bologna city center",
    "lat": 44.4949,
    "lng": 11.3426,
    "status": "city_expansion",
    "gf_notes": "Public expansion guide live; more verified places to follow.",
    "city_url": "/bologna.html"
  },
  {
    "id": 18,
    "name": "Venice Expansion Guide",
    "city": "Venice",
    "country": "Italy",
    "category": "City Guide",
    "badge": "Expansion",
    "badge_class": "yellow",
    "address": "Venice city center",
    "lat": 45.4408,
    "lng": 12.3155,
    "status": "city_expansion",
    "gf_notes": "Public expansion guide live; more verified places to follow.",
    "city_url": "/venice.html"
  }
];