window.CTP_PLACES_DATA = [
  {
    "name": "Quinoa",
    "city": "Florence",
    "category": "Restaurant",
    "subtype": "Restaurant",
    "badge": "Dedicated GF",
    "badge_class": "green",
    "address": "Vicolo di Santa Maria Maggiore 1",
    "lat": 43.774,
    "lng": 11.2522,
    "gf_notes": "Restaurant in Florence. Starter dataset record for CTP."
  },
  {
    "name": "Sgrano",
    "city": "Florence",
    "category": "Bakery",
    "subtype": "Bakery",
    "badge": "Dedicated GF",
    "badge_class": "green",
    "address": "Via dei Neri 34R",
    "lat": 43.7693,
    "lng": 11.2588,
    "gf_notes": "Bakery in Florence. Starter dataset record for CTP."
  },
  {
    "name": "Osteria dello Sgrano",
    "city": "Florence",
    "category": "Restaurant",
    "subtype": "Restaurant",
    "badge": "Dedicated GF",
    "badge_class": "green",
    "address": "Via dei Benci 30",
    "lat": 43.7684,
    "lng": 11.2629,
    "gf_notes": "Restaurant in Florence. Starter dataset record for CTP."
  },
  {
    "name": "Mama Eat Firenze",
    "city": "Florence",
    "category": "Restaurant",
    "subtype": "Restaurant",
    "badge": "Mixed kitchen GF",
    "badge_class": "yellow",
    "address": "Via della Madonna della Tosse 12R",
    "lat": 43.7768,
    "lng": 11.2583,
    "gf_notes": "Restaurant in Florence. Starter dataset record for CTP."
  },
  {
    "name": "Risotteria Melotti",
    "city": "Florence",
    "category": "Restaurant",
    "subtype": "Restaurant",
    "badge": "Dedicated GF",
    "badge_class": "green",
    "address": "Via dei Servi 108R",
    "lat": 43.776,
    "lng": 11.2589,
    "gf_notes": "Restaurant in Florence. Starter dataset record for CTP."
  },
  {
    "name": "Ciro & Sons",
    "city": "Florence",
    "category": "Restaurant / Pizza",
    "subtype": "Restaurant / Pizza",
    "badge": "Mixed kitchen GF",
    "badge_class": "yellow",
    "address": "Via del Giglio 28",
    "lat": 43.7749,
    "lng": 11.2487,
    "gf_notes": "Restaurant / Pizza in Florence. Starter dataset record for CTP."
  },
  {
    "name": "Ristorante Lorenzo de' Medici GF",
    "city": "Florence",
    "category": "Restaurant",
    "subtype": "Restaurant",
    "badge": "Mixed kitchen GF",
    "badge_class": "yellow",
    "address": "Via del Giglio 49",
    "lat": 43.7753,
    "lng": 11.2478,
    "gf_notes": "Restaurant in Florence. Starter dataset record for CTP."
  },
  {
    "name": "Starbene Senza Glutine",
    "city": "Florence",
    "category": "Bakery",
    "subtype": "Bakery",
    "badge": "Dedicated GF",
    "badge_class": "green",
    "address": "Via della Vigna Nuova 10",
    "lat": 43.7719,
    "lng": 11.248,
    "gf_notes": "Bakery in Florence. Starter dataset record for CTP."
  },
  {
    "name": "La Loggia degli Albizi GF",
    "city": "Florence",
    "category": "Restaurant",
    "subtype": "Restaurant",
    "badge": "Mixed kitchen GF",
    "badge_class": "yellow",
    "address": "Via degli Albizi 22",
    "lat": 43.7712,
    "lng": 11.2604,
    "gf_notes": "Restaurant in Florence. Starter dataset record for CTP."
  },
  {
    "name": "Il Vegano GF Option",
    "city": "Florence",
    "category": "Restaurant",
    "subtype": "Restaurant",
    "badge": "Mixed kitchen GF",
    "badge_class": "yellow",
    "address": "Via San Gallo 92",
    "lat": 43.7809,
    "lng": 11.261,
    "gf_notes": "Restaurant in Florence. Starter dataset record for CTP."
  },
  {
    "name": "New Food Experience",
    "city": "Rome",
    "category": "Restaurant",
    "subtype": "Restaurant",
    "badge": "Dedicated GF",
    "badge_class": "green",
    "address": "Via Ostiense 73F",
    "lat": 41.8697,
    "lng": 12.4802,
    "gf_notes": "Restaurant in Rome. Starter dataset record for CTP."
  },
  {
    "name": "Mama Eat Roma",
    "city": "Rome",
    "category": "Restaurant",
    "subtype": "Restaurant",
    "badge": "Mixed kitchen GF",
    "badge_class": "yellow",
    "address": "Via di San Cosimato 7",
    "lat": 41.888,
    "lng": 12.4711,
    "gf_notes": "Restaurant in Rome. Starter dataset record for CTP."
  },
  {
    "name": "La Soffitta Renovatio",
    "city": "Rome",
    "category": "Restaurant / Pizza",
    "subtype": "Restaurant / Pizza",
    "badge": "Mixed kitchen GF",
    "badge_class": "yellow",
    "address": "Piazza del Risorgimento 46A",
    "lat": 41.9085,
    "lng": 12.4589,
    "gf_notes": "Restaurant / Pizza in Rome. Starter dataset record for CTP."
  },
  {
    "name": "Celiachiamo Lab",
    "city": "Rome",
    "category": "Bakery",
    "subtype": "Bakery",
    "badge": "Dedicated GF",
    "badge_class": "green",
    "address": "Via dei Falegnami 9",
    "lat": 41.8945,
    "lng": 12.4798,
    "gf_notes": "Bakery in Rome. Starter dataset record for CTP."
  },
  {
    "name": "Pandali Roma",
    "city": "Rome",
    "category": "Restaurant",
    "subtype": "Restaurant",
    "badge": "Dedicated GF",
    "badge_class": "green",
    "address": "Via di Torre Argentina 3",
    "lat": 41.8958,
    "lng": 12.4775,
    "gf_notes": "Restaurant in Rome. Starter dataset record for CTP."
  },
  {
    "name": "Mama Eat Milano",
    "city": "Milan",
    "category": "Restaurant",
    "subtype": "Restaurant",
    "badge": "Mixed kitchen GF",
    "badge_class": "yellow",
    "address": "Via Giulio Cesare Procaccini 32",
    "lat": 45.4861,
    "lng": 9.1697,
    "gf_notes": "Restaurant in Milan. Starter dataset record for CTP."
  },
  {
    "name": "Officina Zero",
    "city": "Milan",
    "category": "Bakery",
    "subtype": "Bakery",
    "badge": "Dedicated GF",
    "badge_class": "green",
    "address": "Via Thaon di Revel 3",
    "lat": 45.489,
    "lng": 9.1879,
    "gf_notes": "Bakery in Milan. Starter dataset record for CTP."
  },
  {
    "name": "Via dalla Spiga",
    "city": "Milan",
    "category": "Bakery",
    "subtype": "Bakery",
    "badge": "Dedicated GF",
    "badge_class": "green",
    "address": "Via della Spiga 52",
    "lat": 45.4719,
    "lng": 9.1984,
    "gf_notes": "Bakery in Milan. Starter dataset record for CTP."
  },
  {
    "name": "Be Bop Milano GF",
    "city": "Milan",
    "category": "Pizza",
    "subtype": "Pizza",
    "badge": "Mixed kitchen GF",
    "badge_class": "yellow",
    "address": "Viale Col di Lana 4",
    "lat": 45.4465,
    "lng": 9.1798,
    "gf_notes": "Pizza in Milan. Starter dataset record for CTP."
  },
  {
    "name": "Mama Eat Napoli",
    "city": "Naples",
    "category": "Restaurant",
    "subtype": "Restaurant",
    "badge": "Mixed kitchen GF",
    "badge_class": "yellow",
    "address": "Via Toledo area",
    "lat": 40.8427,
    "lng": 14.2505,
    "gf_notes": "Restaurant in Naples. Starter dataset record for CTP."
  },
  {
    "name": "Zero Zero Grano",
    "city": "Naples",
    "category": "Restaurant",
    "subtype": "Restaurant",
    "badge": "Dedicated GF",
    "badge_class": "green",
    "address": "Via San Pasquale 27",
    "lat": 40.8354,
    "lng": 14.2407,
    "gf_notes": "Restaurant in Naples. Starter dataset record for CTP."
  },
  {
    "name": "Leopoldo Gluten Free",
    "city": "Naples",
    "category": "Bakery",
    "subtype": "Bakery",
    "badge": "Mixed kitchen GF",
    "badge_class": "yellow",
    "address": "Via Toledo 214",
    "lat": 40.8428,
    "lng": 14.2482,
    "gf_notes": "Bakery in Naples. Starter dataset record for CTP."
  },
  {
    "name": "Bologna GF Starter",
    "city": "Bologna",
    "category": "Restaurant",
    "subtype": "Restaurant",
    "badge": "GF option",
    "badge_class": "yellow",
    "address": "Centro Bologna",
    "lat": 44.4949,
    "lng": 11.3426,
    "gf_notes": "Restaurant in Bologna. Starter dataset record for CTP."
  },
  {
    "name": "Venice GF Starter",
    "city": "Venice",
    "category": "Restaurant",
    "subtype": "Restaurant",
    "badge": "GF option",
    "badge_class": "yellow",
    "address": "Centro Venezia",
    "lat": 45.4408,
    "lng": 12.3155,
    "gf_notes": "Restaurant in Venice. Starter dataset record for CTP."
  },
  {
    "name": "Prato GF Starter",
    "city": "Prato",
    "category": "Restaurant",
    "subtype": "Restaurant",
    "badge": "GF option",
    "badge_class": "yellow",
    "address": "Centro Prato",
    "lat": 43.8798,
    "lng": 11.0965,
    "gf_notes": "Restaurant in Prato. Starter dataset record for CTP."
  },
  {
    "name": "Pistoia GF Starter",
    "city": "Pistoia",
    "category": "Restaurant",
    "subtype": "Restaurant",
    "badge": "GF option",
    "badge_class": "yellow",
    "address": "Centro Pistoia",
    "lat": 43.933,
    "lng": 10.9179,
    "gf_notes": "Restaurant in Pistoia. Starter dataset record for CTP."
  }
];