window.CTP_PLACES_DATA = [
  {
    "slug": "quinoa-firenze",
    "name": "Quinoa",
    "city": "Florence",
    "city_slug": "florence",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Restaurant",
    "cuisine_type": "Italian",
    "gf_level": "Dedicated GF",
    "trust_level": 5,
    "address": "Vicolo di S. Maria Maggiore 1, Firenze",
    "phone": "",
    "email": "",
    "website": "https://www.ristorantequinoa.it/",
    "instagram": "",
    "menu_url": "https://www.ristorantequinoa.it/",
    "lat": 43.774,
    "lng": 11.2522,
    "description": "Official site says first/only 100% gluten-free restaurant in Florence and AIC certified.",
    "hotel": false
  },
  {
    "slug": "sgrano-firenze-via-dei-neri-firenze",
    "name": "Sgrano Firenze (Via dei Neri)",
    "city": "Florence",
    "city_slug": "florence",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Bakery",
    "cuisine_type": "Bakery / Pastry",
    "gf_level": "Dedicated GF",
    "trust_level": 5,
    "address": "Via dei Neri 49R, Firenze",
    "phone": "",
    "email": "",
    "website": "https://www.sgranoglutenfree.it/sgrano-firenze/",
    "instagram": "",
    "menu_url": "https://www.sgranoglutenfree.it/sgrano-firenze/",
    "lat": 43.7695,
    "lng": 11.2591,
    "description": "Official site presents Sgrano as only gluten-free cuisine and dedicated gluten-free point in Florence.",
    "hotel": false
  },
  {
    "slug": "osteria-dello-sgrano-firenze",
    "name": "Osteria dello Sgrano",
    "city": "Florence",
    "city_slug": "florence",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Restaurant",
    "cuisine_type": "Tuscan / Italian",
    "gf_level": "Dedicated GF",
    "trust_level": 5,
    "address": "Via dei Benci 30R, Firenze",
    "phone": "",
    "email": "",
    "website": "https://www.sgranoglutenfree.it/sgrano-benci/",
    "instagram": "",
    "menu_url": "https://www.sgranoglutenfree.it/sgrano-benci/",
    "lat": 43.7684,
    "lng": 11.2629,
    "description": "Official site describes Osteria dello Sgrano as gluten-free osteria.",
    "hotel": false
  },
  {
    "slug": "risotteria-melotti-firenze-firenze",
    "name": "Risotteria Melotti Firenze",
    "city": "Florence",
    "city_slug": "florence",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Restaurant",
    "cuisine_type": "Italian",
    "gf_level": "Dedicated GF",
    "trust_level": 5,
    "address": "Via dei Servi 65R, Firenze",
    "phone": "",
    "email": "",
    "website": "https://www.risotteriamelottifirenze.it/",
    "instagram": "",
    "menu_url": "https://www.risotteriamelottifirenze.it/",
    "lat": "",
    "lng": "",
    "description": "Official site states 100% senza glutine and only rice/rice-flour dishes.",
    "hotel": false
  },
  {
    "slug": "senza-glutine-firenze-riccardo-gasperini-firenze",
    "name": "Senza Glutine Firenze Riccardo Gasperini",
    "city": "Florence",
    "city_slug": "florence",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Bakery",
    "cuisine_type": "Bakery / Pastry",
    "gf_level": "Dedicated GF",
    "trust_level": 5,
    "address": "Via Pratese 42/D, Firenze",
    "phone": "",
    "email": "",
    "website": "https://riccardogasperinisenzaglutine.it/negozio-senza-glutine-firenze/",
    "instagram": "",
    "menu_url": "https://riccardogasperinisenzaglutine.it/negozio-senza-glutine-firenze/",
    "lat": "",
    "lng": "",
    "description": "Official site describes dedicated gluten-free shop with certified bakery/pastry products; local sources describe all-gluten-free breakfast/fresh counter.",
    "hotel": false
  },
  {
    "slug": "mama-eat-firenze-firenze",
    "name": "Mama Eat Firenze",
    "city": "Florence",
    "city_slug": "florence",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Restaurant / Pizzeria",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 3,
    "address": "Via dell'Acqua 2, Firenze",
    "phone": "",
    "email": "",
    "website": "https://mamaeat.com/en",
    "instagram": "",
    "menu_url": "https://mamaeat.com/en",
    "lat": "",
    "lng": "",
    "description": "Official site says entire menu available gluten-free and locations host two kitchens.",
    "hotel": false
  },
  {
    "slug": "hostaria-il-desco-firenze",
    "name": "Hostaria Il Desco",
    "city": "Florence",
    "city_slug": "florence",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Restaurant",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 3,
    "address": "Via delle Terme 23R, Firenze",
    "phone": "",
    "email": "",
    "website": "https://www.hostariaildesco.com/",
    "instagram": "",
    "menu_url": "https://www.hostariaildesco.com/",
    "lat": "",
    "lng": "",
    "description": "Official site says they are proud to offer cuisine also gluten free; AIC shown on site, but no explicit 100%-dedicated claim found.",
    "hotel": false
  },
  {
    "slug": "lorenzo-de-medici-firenze",
    "name": "Lorenzo de' Medici",
    "city": "Florence",
    "city_slug": "florence",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Restaurant / Pizzeria",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 3,
    "address": "Via del Giglio 49/51R, Firenze",
    "phone": "",
    "email": "",
    "website": "https://www.lorenzodemediciristorante.com/senza-glutine-firenze/",
    "instagram": "",
    "menu_url": "https://www.lorenzodemediciristorante.com/senza-glutine-firenze/",
    "lat": "",
    "lng": "",
    "description": "Official GF page states AIC/AFC inclusion, equipped kitchen, trained staff, menu and pizza for celiacs.",
    "hotel": false
  },
  {
    "slug": "pizzeria-insieme-firenze",
    "name": "Pizzeria Insieme",
    "city": "Florence",
    "city_slug": "florence",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Pizzeria",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 3,
    "address": "Viale Corsica 38A, Firenze",
    "phone": "",
    "email": "",
    "website": "https://www.pizzeriainsieme.it/?lang=it",
    "instagram": "",
    "menu_url": "https://www.pizzeriainsieme.it/?lang=it",
    "lat": "",
    "lng": "",
    "description": "Official site brands itself Gourmet & Gluten Free; user reviews mention gluten-free pizza and desserts.",
    "hotel": false
  },
  {
    "slug": "pizzeria-positano-firenze-firenze",
    "name": "Pizzeria Positano Firenze",
    "city": "Florence",
    "city_slug": "florence",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Pizzeria",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 3,
    "address": "Borgo Ognissanti 84, Firenze",
    "phone": "",
    "email": "",
    "website": "https://pizzeriapositano.eu/pizzeria-positano-firenze/",
    "instagram": "",
    "menu_url": "https://pizzeriapositano.eu/pizzeria-positano-firenze/",
    "lat": "",
    "lng": "",
    "description": "Official brand/site says Positano is among the best pizzerias for celiacs and Florence location aims to be a reference for GF pizza.",
    "hotel": false
  },
  {
    "slug": "ciro-sons-firenze",
    "name": "Ciro & Sons",
    "city": "Florence",
    "city_slug": "florence",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Restaurant / Pizzeria",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 3,
    "address": "Via del Giglio 28/R, Firenze",
    "phone": "",
    "email": "",
    "website": "https://www.opentable.it/r/ciro-and-sons-florence",
    "instagram": "",
    "menu_url": "https://www.opentable.it/r/ciro-and-sons-florence",
    "lat": "",
    "lng": "",
    "description": "OpenTable states entire menu available gluten-free and lactose-free; restaurant is widely known for GF service.",
    "hotel": false
  },
  {
    "slug": "pizza-man-sansovino-gluten-free-senza-lattosio-firenze",
    "name": "Pizza Man Sansovino Gluten Free & Senza Lattosio",
    "city": "Florence",
    "city_slug": "florence",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Pizzeria",
    "cuisine_type": "Pizza",
    "gf_level": "GF Menu Trusted",
    "trust_level": 3,
    "address": "Via del Sansovino 191, Firenze",
    "phone": "",
    "email": "",
    "website": "https://www.thefork.it/ristorante/pizza-man-sansovino-gluten-free-senza-lattosio-r853805",
    "instagram": "",
    "menu_url": "https://www.thefork.it/ristorante/pizza-man-sansovino-gluten-free-senza-lattosio-r853805",
    "lat": "",
    "lng": "",
    "description": "TheFork/Gluto list a specific 'Gluten Free & Senza Lattosio' venue with GF menu focus.",
    "hotel": false
  },
  {
    "slug": "hotel-pendini-firenze",
    "name": "Hotel Pendini",
    "city": "Florence",
    "city_slug": "florence",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Via Strozzi 2, Firenze",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/pendini-firenze.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/pendini-firenze.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists breakfast options including gluten free.",
    "hotel": false
  },
  {
    "slug": "il-guelfo-bianco-firenze",
    "name": "Il Guelfo Bianco",
    "city": "Florence",
    "city_slug": "florence",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Via Cavour 29, Firenze",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/guelfo-bianco.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/guelfo-bianco.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking says buffet breakfast includes gluten-free options.",
    "hotel": false
  },
  {
    "slug": "25hours-hotel-florence-piazza-san-paolino-firenze",
    "name": "25hours Hotel Florence Piazza San Paolino",
    "city": "Florence",
    "city_slug": "florence",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Piazza di San Paolino 1, Firenze",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/25hours-piazza-san-paolino.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/25hours-piazza-san-paolino.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists breakfast options including gluten free.",
    "hotel": false
  },
  {
    "slug": "ruby-bea-hotel-florence-firenze",
    "name": "Ruby Bea Hotel Florence",
    "city": "Florence",
    "city_slug": "florence",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Piazza della Libertà 16, Firenze",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/ruby-bea-florence.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/ruby-bea-florence.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists breakfast in gluten-free version and menus for special diets.",
    "hotel": false
  },
  {
    "slug": "new-food-experience-roma",
    "name": "New Food Experience",
    "city": "Rome",
    "city_slug": "rome",
    "region": "Lazio",
    "province_bucket": "In city",
    "category": "Restaurant",
    "cuisine_type": "Italian",
    "gf_level": "Dedicated GF",
    "trust_level": 5,
    "address": "Viale Mazzini 31, Roma",
    "phone": "",
    "email": "",
    "website": "https://newfoodexperience.it/",
    "instagram": "",
    "menu_url": "https://newfoodexperience.it/",
    "lat": 41.9073,
    "lng": 12.455,
    "description": "Official site says cucina italiana totalmente gluten free.",
    "hotel": false
  },
  {
    "slug": "new-food-gluten-free-roma",
    "name": "New Food Gluten Free",
    "city": "Rome",
    "city_slug": "rome",
    "region": "Lazio",
    "province_bucket": "In city",
    "category": "Bakery",
    "cuisine_type": "Bakery / Pastry",
    "gf_level": "Dedicated GF",
    "trust_level": 5,
    "address": "Roma (multiple points)",
    "phone": "",
    "email": "",
    "website": "https://newfoodglutenfree.it/",
    "instagram": "",
    "menu_url": "https://newfoodglutenfree.it/",
    "lat": "",
    "lng": "",
    "description": "Official site says bakery products safe for celiacs and AIC program adherence.",
    "hotel": false
  },
  {
    "slug": "celiachiamo-prati-roma",
    "name": "Celiachiamo Prati",
    "city": "Rome",
    "city_slug": "rome",
    "region": "Lazio",
    "province_bucket": "In city",
    "category": "Bakery",
    "cuisine_type": "Pizza",
    "gf_level": "Dedicated GF",
    "trust_level": 5,
    "address": "Via Trionfale 15, Roma",
    "phone": "",
    "email": "",
    "website": "https://www.celiachiamo.com/roma-prati/",
    "instagram": "",
    "menu_url": "https://www.celiachiamo.com/roma-prati/",
    "lat": "",
    "lng": "",
    "description": "Official site states all fresh production is 100% gluten free with internal lab.",
    "hotel": false
  },
  {
    "slug": "celiachiamo-eur-roma",
    "name": "Celiachiamo EUR",
    "city": "Rome",
    "city_slug": "rome",
    "region": "Lazio",
    "province_bucket": "In city",
    "category": "Bakery",
    "cuisine_type": "Pizza",
    "gf_level": "Dedicated GF",
    "trust_level": 5,
    "address": "Via Elio Vittorini 49/51, Roma",
    "phone": "",
    "email": "",
    "website": "https://www.celiachiamo.com/roma-eur/",
    "instagram": "",
    "menu_url": "https://www.celiachiamo.com/roma-eur/",
    "lat": "",
    "lng": "",
    "description": "Official site states 200 sqm all gluten free and internal lab with everything fresh 100% GF.",
    "hotel": false
  },
  {
    "slug": "celiachiamo-tuscolana-roma",
    "name": "Celiachiamo Tuscolana",
    "city": "Rome",
    "city_slug": "rome",
    "region": "Lazio",
    "province_bucket": "In city",
    "category": "Bakery",
    "cuisine_type": "Pizza",
    "gf_level": "Dedicated GF",
    "trust_level": 5,
    "address": "Viale dei Consoli 185, Roma",
    "phone": "",
    "email": "",
    "website": "https://www.celiachiamo.com/roma-tuscolana/",
    "instagram": "",
    "menu_url": "https://www.celiachiamo.com/roma-tuscolana/",
    "lat": "",
    "lng": "",
    "description": "Official site states 100% gluten free and mono-dedicated internal production.",
    "hotel": false
  },
  {
    "slug": "forno-celiachiamo-tiburtina-roma",
    "name": "Forno Celiachiamo Tiburtina",
    "city": "Rome",
    "city_slug": "rome",
    "region": "Lazio",
    "province_bucket": "In city",
    "category": "Bakery",
    "cuisine_type": "Bakery / Pastry",
    "gf_level": "Dedicated GF",
    "trust_level": 5,
    "address": "Via Carlo Caneva 40, Roma",
    "phone": "",
    "email": "",
    "website": "https://www.celiachiamo.com/roma-tiburtina/",
    "instagram": "",
    "menu_url": "https://www.celiachiamo.com/roma-tiburtina/",
    "lat": "",
    "lng": "",
    "description": "Official site says fresh production exclusively gluten free.",
    "hotel": false
  },
  {
    "slug": "pandali-roma",
    "name": "Pandali",
    "city": "Rome",
    "city_slug": "rome",
    "region": "Lazio",
    "province_bucket": "In city",
    "category": "Bakery",
    "cuisine_type": "Bakery / Pastry",
    "gf_level": "Dedicated GF",
    "trust_level": 5,
    "address": "Piazza Cenci area, Roma",
    "phone": "",
    "email": "",
    "website": "https://www.tripadvisor.co.uk/Restaurant_Review-g187791-d7649661-Reviews-Pandali-Rome_Lazio.html",
    "instagram": "",
    "menu_url": "https://www.tripadvisor.co.uk/Restaurant_Review-g187791-d7649661-Reviews-Pandali-Rome_Lazio.html",
    "lat": "",
    "lng": "",
    "description": "Tripadvisor review describes it as 100% gluten free and AIC-certified bakery near the Pantheon.",
    "hotel": false
  },
  {
    "slug": "mama-eat-roma-roma",
    "name": "Mama Eat Roma",
    "city": "Rome",
    "city_slug": "rome",
    "region": "Lazio",
    "province_bucket": "In city",
    "category": "Restaurant / Pizzeria",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 3,
    "address": "Via di San Cosimato 7/9, Roma",
    "phone": "",
    "email": "",
    "website": "https://www.glutenfreecuppatea.co.uk/2019/03/12/gluten-free-rome-guide/",
    "instagram": "",
    "menu_url": "https://www.glutenfreecuppatea.co.uk/2019/03/12/gluten-free-rome-guide/",
    "lat": "",
    "lng": "",
    "description": "Widely cited travel guide says every item on menu can be made gluten free; Mama Eat brand uses two kitchens.",
    "hotel": false
  },
  {
    "slug": "albergo-santa-chiara-roma",
    "name": "Albergo Santa Chiara",
    "city": "Rome",
    "city_slug": "rome",
    "region": "Lazio",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Via di Santa Chiara 21, Roma",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/albergo-santa-chiara.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/albergo-santa-chiara.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking states gluten-free products available at breakfast.",
    "hotel": false
  },
  {
    "slug": "bh-hotel-roma",
    "name": "BH Hotel",
    "city": "Rome",
    "city_slug": "rome",
    "region": "Lazio",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Via Palestro 13, Roma",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/bh.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/bh.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast option.",
    "hotel": false
  },
  {
    "slug": "piccolo-hotel-boutique-roma",
    "name": "Piccolo Hotel Boutique",
    "city": "Rome",
    "city_slug": "rome",
    "region": "Lazio",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Via Marsala area, Roma",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/piccolo-botique.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/piccolo-botique.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists continental/Italian/vegetarian/vegan/gluten-free breakfast.",
    "hotel": false
  },
  {
    "slug": "ergife-palace-hotel-roma",
    "name": "Ergife Palace Hotel",
    "city": "Rome",
    "city_slug": "rome",
    "region": "Lazio",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Largo Lorenzo Mossa 4, Roma",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/ergife-palace.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/ergife-palace.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": false
  },
  {
    "slug": "hotel-fiori-roma",
    "name": "Hotel Fiori",
    "city": "Rome",
    "city_slug": "rome",
    "region": "Lazio",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Via Nazionale area, Roma",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/hotelfiorirome.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/hotelfiorirome.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": false
  },
  {
    "slug": "officina-zero-bakery-milano",
    "name": "Officina Zero Bakery",
    "city": "Milan",
    "city_slug": "milan",
    "region": "Lombardy",
    "province_bucket": "In city",
    "category": "Bakery",
    "cuisine_type": "Bakery / Pastry",
    "gf_level": "Dedicated GF",
    "trust_level": 5,
    "address": "Via Andrea Doria 44, Milano",
    "phone": "",
    "email": "",
    "website": "https://www.officinazerobakery.it/",
    "instagram": "",
    "menu_url": "https://www.officinazerobakery.it/",
    "lat": "",
    "lng": "",
    "description": "Official site says all products are 100% gluten free.",
    "hotel": false
  },
  {
    "slug": "via-dalla-spiga-milano",
    "name": "Via dalla Spiga",
    "city": "Milan",
    "city_slug": "milan",
    "region": "Lombardy",
    "province_bucket": "In city",
    "category": "Bakery",
    "cuisine_type": "Bakery / Pastry",
    "gf_level": "Dedicated GF",
    "trust_level": 5,
    "address": "Viale San Michele del Carso 13, Milano",
    "phone": "",
    "email": "",
    "website": "https://www.tripadvisor.it/Restaurant_Review-g187849-d10600526-Reviews-Via_dalla_Spiga-Milan_Lombardy.html",
    "instagram": "",
    "menu_url": "https://www.tripadvisor.it/Restaurant_Review-g187849-d10600526-Reviews-Via_dalla_Spiga-Milan_Lombardy.html",
    "lat": 45.4667,
    "lng": 9.1538,
    "description": "Tripadvisor describes it as first bakery 100% gluten free in Milan.",
    "hotel": false
  },
  {
    "slug": "glufree-bakery-milano",
    "name": "GluFree Bakery",
    "city": "Milan",
    "city_slug": "milan",
    "region": "Lombardy",
    "province_bucket": "In city",
    "category": "Bakery",
    "cuisine_type": "Bakery / Pastry",
    "gf_level": "Dedicated GF",
    "trust_level": 5,
    "address": "Via Curtatone 6, Milano",
    "phone": "",
    "email": "",
    "website": "https://www.instagram.com/glufreebakery/",
    "instagram": "",
    "menu_url": "https://www.instagram.com/glufreebakery/",
    "lat": "",
    "lng": "",
    "description": "Instagram states bakery 100% senza glutine; Gluto describes it as key GF stop.",
    "hotel": false
  },
  {
    "slug": "milano-senza-glutine-milano",
    "name": "Milano Senza Glutine",
    "city": "Milan",
    "city_slug": "milan",
    "region": "Lombardy",
    "province_bucket": "In city",
    "category": "Shop",
    "cuisine_type": "Italian",
    "gf_level": "Dedicated GF",
    "trust_level": 5,
    "address": "Milano (multiple points)",
    "phone": "",
    "email": "",
    "website": "https://www.milanosenzaglutine.it/",
    "instagram": "",
    "menu_url": "https://www.milanosenzaglutine.it/",
    "lat": "",
    "lng": "",
    "description": "Official site presents dedicated world for celiac/intolerant-safe products.",
    "hotel": false
  },
  {
    "slug": "be-bop-milano",
    "name": "Be Bop",
    "city": "Milan",
    "city_slug": "milan",
    "region": "Lombardy",
    "province_bucket": "In city",
    "category": "Restaurant / Pizzeria",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 3,
    "address": "Viale Col di Lana 4, Milano",
    "phone": "",
    "email": "",
    "website": "https://bebopmilano.it/",
    "instagram": "",
    "menu_url": "https://bebopmilano.it/",
    "lat": "",
    "lng": "",
    "description": "Official site says traditional restaurant with vegetarian, vegan and gluten-free menus, plus gluten-free pizzas.",
    "hotel": false
  },
  {
    "slug": "pizzeria-positano-milano-cadorna-milano",
    "name": "Pizzeria Positano Milano Cadorna",
    "city": "Milan",
    "city_slug": "milan",
    "region": "Lombardy",
    "province_bucket": "In city",
    "category": "Pizzeria",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 3,
    "address": "Via Torino/Cadorna area, Milano",
    "phone": "",
    "email": "",
    "website": "https://pizzeriapositano.eu/milano-cadorna/",
    "instagram": "",
    "menu_url": "https://pizzeriapositano.eu/milano-cadorna/",
    "lat": "",
    "lng": "",
    "description": "Official site says vast offer of gluten-free pizzas and AIC-informed pizzeria.",
    "hotel": false
  },
  {
    "slug": "linfa-eat-different-milano",
    "name": "Linfa Eat Different",
    "city": "Milan",
    "city_slug": "milan",
    "region": "Lombardy",
    "province_bucket": "In city",
    "category": "Restaurant",
    "cuisine_type": "Italian",
    "gf_level": "Dedicated GF",
    "trust_level": 5,
    "address": "Via Bergognone area, Milano",
    "phone": "",
    "email": "",
    "website": "https://www.finedininglovers.it/esplora/articoli/24-ore-senza-glutine-milano-la-guida-mangiare-gluten-free-dalla-colazione-alla",
    "instagram": "",
    "menu_url": "https://www.finedininglovers.it/esplora/articoli/24-ore-senza-glutine-milano-la-guida-mangiare-gluten-free-dalla-colazione-alla",
    "lat": "",
    "lng": "",
    "description": "Fine Dining Lovers describes it as first plant-based restaurant in Italy and 100% gluten free.",
    "hotel": false
  },
  {
    "slug": "mama-eat-milano-milano",
    "name": "Mama Eat Milano",
    "city": "Milan",
    "city_slug": "milan",
    "region": "Lombardy",
    "province_bucket": "In city",
    "category": "Restaurant / Pizzeria",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 3,
    "address": "Milano (multiple points)",
    "phone": "",
    "email": "",
    "website": "https://valeriaglutenfree.com/dove-mangiare-senza-glutine-a-milano/",
    "instagram": "",
    "menu_url": "https://valeriaglutenfree.com/dove-mangiare-senza-glutine-a-milano/",
    "lat": "",
    "lng": "",
    "description": "GF guide notes two separate kitchens, one dedicated to gluten free.",
    "hotel": false
  },
  {
    "slug": "hotel-fenice-gluten-free-milano",
    "name": "Hotel Fenice Gluten Free",
    "city": "Milan",
    "city_slug": "milan",
    "region": "Lombardy",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Corso Buenos Aires 2, Milano",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/fenice.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/fenice.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists buffet/continental/gluten-free breakfast.",
    "hotel": false
  },
  {
    "slug": "hotel-degli-arcimboldi-milano",
    "name": "Hotel degli Arcimboldi",
    "city": "Milan",
    "city_slug": "milan",
    "region": "Lombardy",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Viale Sarca 336, Milano",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/hotel-degli-arcimboldi.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/hotel-degli-arcimboldi.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast option.",
    "hotel": false
  },
  {
    "slug": "hotel-gamma-milano",
    "name": "Hotel Gamma",
    "city": "Milan",
    "city_slug": "milan",
    "region": "Lombardy",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Via Vallazze 14, Milano",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/hotelgammamilano.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/hotelgammamilano.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": false
  },
  {
    "slug": "windsor-hotel-milano-milano",
    "name": "Windsor Hotel Milano",
    "city": "Milan",
    "city_slug": "milan",
    "region": "Lombardy",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Via Galileo Galilei 2, Milano",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/windsor.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/windsor.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": false
  },
  {
    "slug": "townhouse-33-boutique-hotel-milano",
    "name": "TownHouse 33 Boutique Hotel",
    "city": "Milan",
    "city_slug": "milan",
    "region": "Lombardy",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Via Goldoni 33, Milano",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/townhouse-33.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/townhouse-33.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": false
  },
  {
    "slug": "zero-zero-grano-napoli",
    "name": "Zero Zero Grano",
    "city": "Naples",
    "city_slug": "naples",
    "region": "Campania",
    "province_bucket": "In city",
    "category": "Restaurant",
    "cuisine_type": "Italian",
    "gf_level": "Dedicated GF",
    "trust_level": 5,
    "address": "Via Nardones 11, Napoli",
    "phone": "",
    "email": "",
    "website": "https://www.facebook.com/zerozerograno/?locale=it_IT",
    "instagram": "",
    "menu_url": "https://www.facebook.com/zerozerograno/?locale=it_IT",
    "lat": 40.8354,
    "lng": 14.2407,
    "description": "Facebook page and Tripadvisor describe it as 100% gluten free and lactose free with complete safety.",
    "hotel": false
  },
  {
    "slug": "vitto-pitagorico-napoli",
    "name": "Vitto Pitagorico",
    "city": "Naples",
    "city_slug": "naples",
    "region": "Campania",
    "province_bucket": "In city",
    "category": "Restaurant",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 3,
    "address": "Via Enrico Alvino area, Napoli",
    "phone": "",
    "email": "",
    "website": "https://www.vittopitagorico.it/",
    "instagram": "",
    "menu_url": "https://www.vittopitagorico.it/",
    "lat": "",
    "lng": "",
    "description": "Official site presents restaurant as vegan/vegetarian/raw with gluten-free dishes.",
    "hotel": false
  },
  {
    "slug": "1000-gourmet-gruppo-1000-napoli",
    "name": "1000 Gourmet (Gruppo 1000)",
    "city": "Naples",
    "city_slug": "naples",
    "region": "Campania",
    "province_bucket": "In city",
    "category": "Pizzeria / Restaurant",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 3,
    "address": "Napoli",
    "phone": "",
    "email": "",
    "website": "https://gruppo1000.com/",
    "instagram": "",
    "menu_url": "https://gruppo1000.com/",
    "lat": "",
    "lng": "",
    "description": "Official group site says 1000 Gourmet offers gluten-free version among formats.",
    "hotel": false
  },
  {
    "slug": "casa-qboo-pizzeria-trattoria-gluten-free-napoli",
    "name": "Casa Qboo Pizzeria Trattoria Gluten Free",
    "city": "Naples",
    "city_slug": "naples",
    "region": "Campania",
    "province_bucket": "In city",
    "category": "Restaurant / Pizzeria",
    "cuisine_type": "Tuscan / Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 3,
    "address": "Napoli",
    "phone": "",
    "email": "",
    "website": "https://www.thefork.it/ristorante/casa-qboo-pizzeria-trattoria-gluten-free-r747405",
    "instagram": "",
    "menu_url": "https://www.thefork.it/ristorante/casa-qboo-pizzeria-trattoria-gluten-free-r747405",
    "lat": "",
    "lng": "",
    "description": "TheFork describes it as gluten-free pizzeria/trattoria with positive customer feedback.",
    "hotel": false
  },
  {
    "slug": "palazzo-firenze-napoli",
    "name": "Palazzo Firenze",
    "city": "Naples",
    "city_slug": "naples",
    "region": "Campania",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Via Firenze 16, Napoli",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/palazzo-firenze.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/palazzo-firenze.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": false
  },
  {
    "slug": "una-hotels-napoli-napoli",
    "name": "UNA HOTELS Napoli",
    "city": "Naples",
    "city_slug": "naples",
    "region": "Campania",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Piazza Garibaldi 9/10, Napoli",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/unahotel-napoli.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/unahotel-napoli.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking says gluten-free options available on request at breakfast.",
    "hotel": false
  },
  {
    "slug": "villa-elisio-hotel-spa-napoli",
    "name": "Villa Elisio Hotel & Spa",
    "city": "Naples",
    "city_slug": "naples",
    "region": "Campania",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Via Luca Samuele Cagnazzi 29, Napoli",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/villa-elisio-amp-spa.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/villa-elisio-amp-spa.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": false
  },
  {
    "slug": "suite-dei-catalani-napoli",
    "name": "Suite dei Catalani",
    "city": "Naples",
    "city_slug": "naples",
    "region": "Campania",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Via Agostino Depretis 78, Napoli",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/suite-dei-catalani.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/suite-dei-catalani.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": false
  },
  {
    "slug": "b-b-chiaia-32-napoli",
    "name": "B&B Chiaia 32",
    "city": "Naples",
    "city_slug": "naples",
    "region": "Campania",
    "province_bucket": "In city",
    "category": "B&B",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Via Chiaia 32, Napoli",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/bed-breakfast-chiaia-32.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/bed-breakfast-chiaia-32.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists Italian and gluten-free breakfast.",
    "hotel": false
  },
  {
    "slug": "antichi-sapori-prato",
    "name": "Antichi Sapori",
    "city": "Prato",
    "city_slug": "prato",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Restaurant / Pizzeria",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 3,
    "address": "Via Vittorio da Filicaia 40, Prato",
    "phone": "",
    "email": "",
    "website": "https://antichisaporiprato.it/",
    "instagram": "",
    "menu_url": "https://antichisaporiprato.it/",
    "lat": "",
    "lng": "",
    "description": "Official site highlights extensive a la carte menu dedicated to celiacs; Tripadvisor review mentions separate kitchen for safe prep.",
    "hotel": false
  },
  {
    "slug": "hotel-giardino-prato",
    "name": "Hotel Giardino",
    "city": "Prato",
    "city_slug": "prato",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Piazza Mercatale 14, Prato",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/giardino.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/giardino.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": false
  },
  {
    "slug": "art-hotel-museo-prato",
    "name": "Art Hotel Museo",
    "city": "Prato",
    "city_slug": "prato",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Viale della Repubblica 289, Prato",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/arthotelmuseo.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/arthotelmuseo.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking notes restaurant with vegetarian and gluten-free options plus buffet breakfast.",
    "hotel": false
  },
  {
    "slug": "boutique-hotel-enia-prato",
    "name": "Boutique Hotel Enia",
    "city": "Prato",
    "city_slug": "prato",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Via Ferrucci area, Prato",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/boutique-enia.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/boutique-enia.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": false
  },
  {
    "slug": "petit-hotel-prato",
    "name": "Petit Hotel",
    "city": "Prato",
    "city_slug": "prato",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Via Torquato Tasso area, Prato",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/petit-prato.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/petit-prato.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": false
  },
  {
    "slug": "villa-rucellai-prato",
    "name": "Villa Rucellai",
    "city": "Prato",
    "city_slug": "prato",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "B&B / historic villa",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Via di Canneto 16, Prato",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/villa-rucellai-fattoria-di-canneto.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/villa-rucellai-fattoria-di-canneto.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": false
  },
  {
    "slug": "charme-hotel-prato",
    "name": "Charme Hotel",
    "city": "Prato",
    "city_slug": "prato",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Via delle Badie 228, Prato",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/charme.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/charme.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": false
  },
  {
    "slug": "d-era-bistrot-pistoia",
    "name": "D'Era Bistrot",
    "city": "Pistoia",
    "city_slug": "pistoia",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Restaurant",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 3,
    "address": "Via del Lastrone 21, Pistoia",
    "phone": "",
    "email": "",
    "website": "https://www.tripadvisor.it/Restaurant_Review-g194851-d21319938-Reviews-D_era_Bistrot-Pistoia_Province_of_Pistoia_Tuscany.html",
    "instagram": "",
    "menu_url": "https://www.tripadvisor.it/Restaurant_Review-g194851-d21319938-Reviews-D_era_Bistrot-Pistoia_Province_of_Pistoia_Tuscany.html",
    "lat": "",
    "lng": "",
    "description": "Tripadvisor reviews indicate almost all dishes can be replicated gluten free.",
    "hotel": false
  },
  {
    "slug": "hotel-patria-pistoia",
    "name": "Hotel Patria",
    "city": "Pistoia",
    "city_slug": "pistoia",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Via Francesco Crispi 8, Pistoia",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/patria-pistoia.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/patria-pistoia.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": false
  },
  {
    "slug": "il-mulino-di-celle-pistoia",
    "name": "Il Mulino di Celle",
    "city": "Pistoia",
    "city_slug": "pistoia",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Agriturismo / Inn",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Via Montalese 117, Pistoia",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/il-mulino-di-celle.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/il-mulino-di-celle.html",
    "lat": "",
    "lng": "",
    "description": "Booking says traditional restaurant serves Italian cuisine with vegetarian, gluten-free and dairy-free options; breakfast includes local specialties.",
    "hotel": false
  },
  {
    "slug": "villa-giorgia-albergo-in-collina-pistoia",
    "name": "Villa Giorgia Albergo in Collina",
    "city": "Pistoia",
    "city_slug": "pistoia",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Via Bolognese 164, Pistoia",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/villa-giorgia.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/villa-giorgia.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": false
  },
  {
    "slug": "all-ombra-del-tiglio-pistoia",
    "name": "All'Ombra Del Tiglio",
    "city": "Pistoia",
    "city_slug": "pistoia",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Agriturismo",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Pistoia countryside",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/all-ombra-del-tiglio.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/all-ombra-del-tiglio.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": false
  },
  {
    "slug": "campus-vannucci-agriturismo-in-citta-pistoia",
    "name": "Campus Vannucci - agriturismo in città",
    "city": "Pistoia",
    "city_slug": "pistoia",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Agriturismo / city farm stay",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Via Bonellina area, Pistoia",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/pistoia-nurserycampus.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/pistoia-nurserycampus.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": false
  },
  {
    "slug": "agriturismo-villa-bracali-pistoia",
    "name": "Agriturismo Villa Bracali",
    "city": "Pistoia",
    "city_slug": "pistoia",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Agriturismo",
    "cuisine_type": "Italian",
    "gf_level": "GF Menu Trusted",
    "trust_level": 1,
    "address": "Serravalle Pistoiese",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/villa-bracali.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/villa-bracali.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": false
  },
  {
    "slug": "florence-hotel-pendini",
    "name": "Hotel Pendini",
    "city": "Florence",
    "city_slug": "florence",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/pendini-firenze.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/pendini-firenze.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists breakfast options including gluten free.",
    "hotel": true
  },
  {
    "slug": "florence-il-guelfo-bianco",
    "name": "Il Guelfo Bianco",
    "city": "Florence",
    "city_slug": "florence",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/guelfo-bianco.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/guelfo-bianco.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking says buffet breakfast includes gluten-free options.",
    "hotel": true
  },
  {
    "slug": "florence-25hours-hotel-florence-piazza-san-paolino",
    "name": "25hours Hotel Florence Piazza San Paolino",
    "city": "Florence",
    "city_slug": "florence",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/25hours-piazza-san-paolino.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/25hours-piazza-san-paolino.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists breakfast options including gluten free.",
    "hotel": true
  },
  {
    "slug": "florence-ruby-bea-hotel-florence",
    "name": "Ruby Bea Hotel Florence",
    "city": "Florence",
    "city_slug": "florence",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/ruby-bea-florence.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/ruby-bea-florence.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists breakfast in gluten-free version and menus for special diets.",
    "hotel": true
  },
  {
    "slug": "rome-albergo-santa-chiara",
    "name": "Albergo Santa Chiara",
    "city": "Rome",
    "city_slug": "rome",
    "region": "Lazio",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/albergo-santa-chiara.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/albergo-santa-chiara.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking states gluten-free products available at breakfast.",
    "hotel": true
  },
  {
    "slug": "rome-bh-hotel",
    "name": "BH Hotel",
    "city": "Rome",
    "city_slug": "rome",
    "region": "Lazio",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/bh.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/bh.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast option.",
    "hotel": true
  },
  {
    "slug": "rome-piccolo-hotel-boutique",
    "name": "Piccolo Hotel Boutique",
    "city": "Rome",
    "city_slug": "rome",
    "region": "Lazio",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/piccolo-botique.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/piccolo-botique.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists continental/Italian/vegetarian/vegan/gluten-free breakfast.",
    "hotel": true
  },
  {
    "slug": "rome-ergife-palace-hotel",
    "name": "Ergife Palace Hotel",
    "city": "Rome",
    "city_slug": "rome",
    "region": "Lazio",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/ergife-palace.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/ergife-palace.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": true
  },
  {
    "slug": "rome-hotel-fiori",
    "name": "Hotel Fiori",
    "city": "Rome",
    "city_slug": "rome",
    "region": "Lazio",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/hotelfiorirome.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/hotelfiorirome.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": true
  },
  {
    "slug": "milan-hotel-fenice-gluten-free",
    "name": "Hotel Fenice Gluten Free",
    "city": "Milan",
    "city_slug": "milan",
    "region": "Lombardy",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/fenice.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/fenice.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists buffet/continental/gluten-free breakfast.",
    "hotel": true
  },
  {
    "slug": "milan-hotel-degli-arcimboldi",
    "name": "Hotel degli Arcimboldi",
    "city": "Milan",
    "city_slug": "milan",
    "region": "Lombardy",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/hotel-degli-arcimboldi.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/hotel-degli-arcimboldi.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast option.",
    "hotel": true
  },
  {
    "slug": "milan-hotel-gamma",
    "name": "Hotel Gamma",
    "city": "Milan",
    "city_slug": "milan",
    "region": "Lombardy",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/hotelgammamilano.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/hotelgammamilano.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": true
  },
  {
    "slug": "milan-windsor-hotel-milano",
    "name": "Windsor Hotel Milano",
    "city": "Milan",
    "city_slug": "milan",
    "region": "Lombardy",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/windsor.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/windsor.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": true
  },
  {
    "slug": "milan-townhouse-33-boutique-hotel",
    "name": "TownHouse 33 Boutique Hotel",
    "city": "Milan",
    "city_slug": "milan",
    "region": "Lombardy",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/townhouse-33.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/townhouse-33.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": true
  },
  {
    "slug": "naples-palazzo-firenze",
    "name": "Palazzo Firenze",
    "city": "Naples",
    "city_slug": "naples",
    "region": "Campania",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/palazzo-firenze.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/palazzo-firenze.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": true
  },
  {
    "slug": "naples-una-hotels-napoli",
    "name": "UNA HOTELS Napoli",
    "city": "Naples",
    "city_slug": "naples",
    "region": "Campania",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "Hospitality",
    "trust_level": 2,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/unahotel-napoli.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/unahotel-napoli.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking says gluten-free options available on request at breakfast.",
    "hotel": true
  },
  {
    "slug": "naples-villa-elisio-hotel-&-spa",
    "name": "Villa Elisio Hotel & Spa",
    "city": "Naples",
    "city_slug": "naples",
    "region": "Campania",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/villa-elisio-amp-spa.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/villa-elisio-amp-spa.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": true
  },
  {
    "slug": "naples-suite-dei-catalani",
    "name": "Suite dei Catalani",
    "city": "Naples",
    "city_slug": "naples",
    "region": "Campania",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/suite-dei-catalani.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/suite-dei-catalani.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": true
  },
  {
    "slug": "naples-b&b-chiaia-32",
    "name": "B&B Chiaia 32",
    "city": "Naples",
    "city_slug": "naples",
    "region": "Campania",
    "province_bucket": "In city",
    "category": "B&B",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/bed-breakfast-chiaia-32.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/bed-breakfast-chiaia-32.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists Italian and gluten-free breakfast.",
    "hotel": true
  },
  {
    "slug": "prato-hotel-giardino",
    "name": "Hotel Giardino",
    "city": "Prato",
    "city_slug": "prato",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/giardino.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/giardino.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": true
  },
  {
    "slug": "prato-art-hotel-museo",
    "name": "Art Hotel Museo",
    "city": "Prato",
    "city_slug": "prato",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/arthotelmuseo.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/arthotelmuseo.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking notes restaurant with vegetarian and gluten-free options plus buffet breakfast.",
    "hotel": true
  },
  {
    "slug": "prato-boutique-hotel-enia",
    "name": "Boutique Hotel Enia",
    "city": "Prato",
    "city_slug": "prato",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/boutique-enia.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/boutique-enia.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": true
  },
  {
    "slug": "prato-petit-hotel",
    "name": "Petit Hotel",
    "city": "Prato",
    "city_slug": "prato",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/petit-prato.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/petit-prato.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": true
  },
  {
    "slug": "prato-villa-rucellai",
    "name": "Villa Rucellai",
    "city": "Prato",
    "city_slug": "prato",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "B&B",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/villa-rucellai-fattoria-di-canneto.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/villa-rucellai-fattoria-di-canneto.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": true
  },
  {
    "slug": "prato-charme-hotel",
    "name": "Charme Hotel",
    "city": "Prato",
    "city_slug": "prato",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/charme.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/charme.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": true
  },
  {
    "slug": "pistoia-hotel-patria",
    "name": "Hotel Patria",
    "city": "Pistoia",
    "city_slug": "pistoia",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/patria-pistoia.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/patria-pistoia.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": true
  },
  {
    "slug": "pistoia-il-mulino-di-celle",
    "name": "Il Mulino di Celle",
    "city": "Pistoia",
    "city_slug": "pistoia",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Agriturismo",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/il-mulino-di-celle.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/il-mulino-di-celle.html",
    "lat": "",
    "lng": "",
    "description": "Booking says traditional restaurant serves Italian cuisine with vegetarian, gluten-free and dairy-free options; breakfast includes local specialties.",
    "hotel": true
  },
  {
    "slug": "pistoia-villa-giorgia-albergo-in-collina",
    "name": "Villa Giorgia Albergo in Collina",
    "city": "Pistoia",
    "city_slug": "pistoia",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/villa-giorgia.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/villa-giorgia.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": true
  },
  {
    "slug": "pistoia-allombra-del-tiglio",
    "name": "All'Ombra Del Tiglio",
    "city": "Pistoia",
    "city_slug": "pistoia",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Agriturismo",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/all-ombra-del-tiglio.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/all-ombra-del-tiglio.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": true
  },
  {
    "slug": "pistoia-campus-vannucci---agriturismo-in-città",
    "name": "Campus Vannucci - agriturismo in città",
    "city": "Pistoia",
    "city_slug": "pistoia",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Agriturismo",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/pistoia-nurserycampus.it.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/pistoia-nurserycampus.it.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": true
  },
  {
    "slug": "pistoia-agriturismo-villa-bracali",
    "name": "Agriturismo Villa Bracali",
    "city": "Pistoia",
    "city_slug": "pistoia",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Agriturismo",
    "cuisine_type": "",
    "gf_level": "GF Breakfast",
    "trust_level": 3,
    "address": "",
    "phone": "",
    "email": "",
    "website": "https://www.booking.com/hotel/it/villa-bracali.html",
    "instagram": "",
    "menu_url": "https://www.booking.com/hotel/it/villa-bracali.html",
    "lat": "",
    "lng": "",
    "description": "Booking lists gluten-free breakfast.",
    "hotel": true
  },
  {
    "slug": "pistoia-agriturismo-pelliccia",
    "name": "Agriturismo Pelliccia",
    "city": "Pistoia",
    "city_slug": "pistoia",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Agriturismo",
    "cuisine_type": "",
    "gf_level": "Hospitality",
    "trust_level": 2,
    "address": "",
    "phone": "",
    "email": "",
    "website": "User file",
    "instagram": "",
    "menu_url": "User file",
    "lat": "",
    "lng": "",
    "description": "From user file only.",
    "hotel": true
  },
  {
    "slug": "pistoia-albergo-regina",
    "name": "Albergo Regina",
    "city": "Pistoia",
    "city_slug": "pistoia",
    "region": "Tuscany",
    "province_bucket": "In city",
    "category": "Hotel",
    "cuisine_type": "",
    "gf_level": "Hospitality",
    "trust_level": 2,
    "address": "",
    "phone": "",
    "email": "",
    "website": "User file",
    "instagram": "",
    "menu_url": "User file",
    "lat": "",
    "lng": "",
    "description": "From user file only.",
    "hotel": true
  }
];
window.CTP_DESTINATIONS = [
  {
    "slug": "cinque-terre",
    "title": "Cinque Terre",
    "subtitle": "Monterosso · Vernazza · Corniglia · Manarola · Riomaggiore"
  },
  {
    "slug": "amalfi-coast",
    "title": "Amalfi Coast",
    "subtitle": "Amalfi · Positano · Ravello · Praiano"
  },
  {
    "slug": "capri",
    "title": "Capri",
    "subtitle": "Capri island"
  },
  {
    "slug": "lake-garda",
    "title": "Lake Garda",
    "subtitle": "Sirmione · Desenzano · Peschiera · Malcesine"
  },
  {
    "slug": "lake-como",
    "title": "Lake Como",
    "subtitle": "Como · Bellagio · Varenna · Menaggio"
  }
];